# Site settings
title: David Beesley
email: hello@davidbeesley.co.uk
description: > #
 Hi, I'm David, and I'm a Front End Web Developer based in Gloucestershire, UK  
baseurl: ""
url: "http://davidbeesley.co.uk"
twitter_username: davebeesley
github_username:  davebeesley

# Build settings
markdown: kramdown
highlighter: pygments
encoding: utf-8
permalink: /blog/:year/:month/:title
paginate: 5
sass:
    style: compressed

gems:
  - jekyll-sitemap